services:
  OxidEsales\EshopCommunity\Internal\Adapter\ShopAdapterInterface:
    class: OxidEsales\EshopCommunity\Internal\Adapter\ShopAdapter
    autowire: true
    public: false

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\ContentFactory:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\ContentFactory

  # TemplateLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\SeoUrlLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\SeoUrlLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\AddUrlParametersLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\AddUrlParametersLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\AssignAdvancedLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\AssignAdvancedLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\IncludeDynamicLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\IncludeDynamicLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\IfContentLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\IfContentLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\FormatPriceLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\FormatPriceLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\ScriptLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\ScriptLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\FormDateLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\FormDateLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\MultiLangLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\MultiLangLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\FormatTimeLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\FormatTimeLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\FileSizeLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\FileSizeLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\StyleLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\StyleLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\TruncateLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\TruncateLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\TranslateSalutationLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\TranslateSalutationLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\NumberFormatLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\NumberFormatLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\WordWrapLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\WordWrapLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\IncludeWidgetLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\IncludeWidgetLogic

  OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\SmartWordWrapLogic:
    class: OxidEsales\EshopCommunity\Internal\Adapter\TemplateLogic\SmartWordWrapLogic


