services:
  _defaults:
    autowire: true
    public: false

  OxidEsales\Eshop\Core\Config:
    class: OxidEsales\Eshop\Core\Config
    factory: ['OxidEsales\Eshop\Core\Registry', 'getConfig']
  OxidEsales\Eshop\Core\UtilsView:
    class: OxidEsales\Eshop\Core\UtilsView
    factory: ['OxidEsales\Eshop\Core\Registry', 'getUtilsView']
  OxidEsales\EshopCommunity\Internal\Framework\Smarty\SmartyContextInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\SmartyContext
  OxidEsales\EshopCommunity\Internal\Framework\Smarty\SmartyBuilderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\SmartyBuilder
  OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartyConfigurationFactoryInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartyConfigurationFactory
  OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartySettingsDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartySettingsDataProvider
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Framework\Smarty\SmartyContextInterface'
      - '@OxidEsales\EshopCommunity\Internal\Framework\Smarty\Extension\SmartyTemplateHandlerInterface'
      - '@oxid_esales.symfony.file_system'
  OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartySecuritySettingsDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartySecuritySettingsDataProvider
  OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartyResourcesDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartyResourcesDataProvider
  OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartyPrefiltersDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartyPrefiltersDataProvider
  OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartyPluginsDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartyPluginsDataProvider
  OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartyConfigurationInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartyConfiguration
    factory: ['@OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartyConfigurationFactoryInterface', 'getConfiguration']
  OxidEsales\EshopCommunity\Internal\Framework\Smarty\Bridge\SmartyEngineBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\Bridge\SmartyEngineBridge
  smarty.smarty_engine_factory:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\SmartyEngineFactory
  OxidEsales\EshopCommunity\Internal\Framework\Templating\TemplateEngineInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\SmartyEngine
    factory: ['@smarty.smarty_engine_factory', 'getTemplateEngine']
  OxidEsales\EshopCommunity\Internal\Framework\Templating\TemplateRendererBridgeInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\Bridge\SmartyTemplateRendererBridge
    public: true
  OxidEsales\EshopCommunity\Internal\Framework\Smarty\Extension\SmartyTemplateHandlerInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\Extension\SmartyDefaultTemplateHandler
  OxidEsales\EshopCommunity\Internal\Framework\Smarty\Extension\ResourcePluginInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\Extension\CacheResourcePlugin
  OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\ModuleSmartyPluginsDataProviderInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\ModuleSmartyPluginsDataProvider
    decorates: OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\SmartyPluginsDataProviderInterface
    decoration_priority: 100
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Framework\Smarty\Configuration\ModuleSmartyPluginsDataProviderInterface.inner'
      - '@OxidEsales\EshopCommunity\Internal\Transition\Adapter\ShopAdapterInterface'
  OxidEsales\EshopCommunity\Internal\Framework\Templating\Cache\CacheClearerInterface:
    class: OxidEsales\EshopCommunity\Internal\Framework\Smarty\Cache\TemplateCacheClearer
    arguments:
      - '@OxidEsales\EshopCommunity\Internal\Framework\Templating\TemplateEngineInterface'
    public: true